apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: nl-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: Zoznam čakajúcich nl # napr. "Zoznam čakajúcich <pfx>"
  description: "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii" # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Ľubomír Novotný" # Zadajte mená autorov
  azureLink: "https://nl-ambulance-cab8ebfgc7fyfven.westeurope-01.azurewebsites.net"
  frontendRepoUrl: "https://github.com/GreenDev1/ambulance-ufe"
  backendRepoUrl: "https://github.com/GreenDev1/ambulance-webapi"
  gitopsRepoUrl: "https://github.com/GreenDev1/ambulance-gitops"