apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: greendev15/ambulance-ufe
  newName: greendev15/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260224.1159 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
